UHF-2604: Ontology word details
City-of-Helsinki/drupal-module-helfi-tpr pull request #83
Opened 2021-12-21 08:06 UTC by tapsal

Adds import for "ontology word details" and adds a new entity "OntologyWordDetails" for them. When these are imported, they are automatically published if the relevant Unit entity is also published.

For now, these are only used to get information high school search filtering.

**How to test:**
* Setup up Kasko development environment.
* Check out Kasko branch `UHF-2604-kasko-ontology_word_details`.
* Get the changes for this module: `composer require drupal/helfi_tpr:dev-UHF-2604-ontology_word_details`
* Run database updates: `drush updb`
* Import configs: `drush cim`
* Clear caches: `drush cr`
* Make sure you have imported tpr_units including Helsinki's upper secondary schools (you can use [this](https://www.hel.fi/helsinki/fi/kasvatus-ja-koulutus/lukiot/opiskelu/lukioiden-painotukset/) list).
  * Publish those upper secondary schools units (and maybe also e.g. Swedish translations)
* Make sure you have a landing page with High school search component.
  * ...and those published schools are added to that search.
* Run: `drush migrate:import tpr_ontology_word_details`
* Now open the page containing the High school search and you should be able to filter the results using the "Select a special emphasis or study programme" and "Select a special educational mission" fields.

2021-12-21 10:08 UTC, tuutti requested changes

2021-12-21 10:08 UTC, tuutti commented on src/Plugin/views/filter/EducationalMission.php
> +
Missing `declare(strict_types=1)`

2021-12-21 10:08 UTC, tuutti commented on src/Plugin/views/filter/Emphasis.php
> +<?php
Missing declare(strict_types=1)

2021-12-21 10:08 UTC, tuutti commented on src/Plugin/views/filter/OntologyWordDetailsBase.php
> +<?php
Missing declare(strict_types=1)

2021-12-21 10:08 UTC, tuutti commented on src/Plugin/Field/FieldFormatter/SchoolDetailsFormatter.php
> +        '#clarification' => Html::escape($item->get('clarification')->getValue()),
This is escaped twice I think. Here and in twig template.

2021-12-21 10:08 UTC, tuutti commented on src/Plugin/Field/FieldFormatter/SchoolDetailsFormatter.php
> +        '#schoolyear' => Html::escape($item->get('schoolyear')->getValue()),
Same as above.

2021-12-21 10:11 UTC, tuutti commented on src/Plugin/migrate/process/PublishByUnit.php
> +    if (!empty($unit) && $unit->get('content_translation_status')->getString() === '1') {
Call `$unit->isPublished()` instead.

2021-12-21 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['ontologyword_id'] = static::createStringField('Ontology word ID')
No, the entity's ID field is just `id` (so it's generated by the RemoteEntityBase). These entities are basically a combination of units and ontologywords. However, as the migration source lacks a proper ID for that combination, the migration uses ontologyword_id and unit_id as source IDs and then the ID for the entity is generated based on that combination. This is done at the source plugin.

2022-01-04 12:55 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_source'] = BaseFieldDefinition::create('language')
For some reason the content translation fields were not created when content translation support was enabled for this entity type. As the fields were previously created for other entity types using an update hook, these fields are now also now created by using another update hook.

2022-01-04 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_outdated'] = BaseFieldDefinition::create('boolean')
See comment above.

2022-01-04 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_uid'] = BaseFieldDefinition::create('entity_reference')
See comment above.

2022-01-04 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_status'] = BaseFieldDefinition::create('boolean')
See comment above.

2022-01-04 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_created'] = BaseFieldDefinition::create('created')
See comment above.

2022-01-04 12:56 UTC, tapsal commented on src/Entity/OntologyWordDetails.php
> +    $fields['content_translation_changed'] = BaseFieldDefinition::create('changed')
See comment above.

2022-01-11 07:33 UTC, tuutti approved these changes

2022-01-11 08:20 UTC, merged